---

- block:
  - name: Download and unpack Erd release tarball
    unarchive:
      src: "{{erd_release_url}}"
      dest: "{{source_releases_data_dir}}"
      remote_src: yes

  - name: Install Erd release
    community.general.pipx:
      executable: "{{pipx_executable_path}}"
      name: erd
      source: "{{erd_release_dir}}"
      state: latest

- name: Link Erd RC file
  file:
    src: "{{dotfiles_src_dir}}/erd/erd.rc"
    dest: "{{erd_config_file}}"
    state: link
    follow: no
    force: yes
