---

- name: Ensure ~/.ssh directory exists
  file:
    dest: ~/.ssh
    state: directory
    mode: 0700

- name: Ensure ~/.ssh/config.d directory exists
  file:
    dest: ~/.ssh/config.d
    state: directory
    mode: 0700

- name: Link SSH client config
  file:
    src: "{{dotfiles_src_dir}}/ssh/config"
    dest: ~/.ssh/config
    state: link
    follow: no
    force: yes
