#!/usr/bin/env python3

if __name__ == "__main__":
    for c in range(0, 16):
        print(f"\x1b[38;5;{c}m{c:>6}\x1b[0m", end="")
    print()
    for i in range(0, 10):
        for j in range(0, 24):
            c = 16 + i * 24 + j
            print(f"\x1b[38;5;{c}m{c:>4}\x1b[0m", end="")
        print()
