#!/usr/bin/env bash
set -euo pipefail

function foreach_path() {
  while IFS=: read -d: -r path; do
    echo $path
  done <<<"${PATH:+"${PATH}:"}"
}

clang_format="$(
  foreach_path |
    xargs -I{} find {} -maxdepth 1 -name 'clang-format-*.*' |
    sort --reverse --version-sort --field-separator=- --key=3,3 |
    head --lines=1
)"

if [ -z "$clang_format" ]; then
  echo command not found: clang-format* >&2
  exit 127
fi

exec "$clang_format" "$@"
