if patched_font_in_use; then
  TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
  TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
  TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
  TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
  TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
  TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
  TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
  TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR="$COLOR_SELECTOR_DARK"
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR="$COLOR_SELECTOR_LIGHT"

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR="$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD"
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR="$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD"

# Format: segment_name background_color foreground_color [non_default_separator]

TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
  "tmux_session_info $COLOR_SELECTOR_LIGHT $COLOR_SELECTOR_DARK"
  "hostname $COLOR_SELECTOR_DARK $COLOR_SELECTOR_LIGHT"
  "vcs_branch $COLOR_SELECTOR_LIGHT $COLOR_SELECTOR_DARK $TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
  "pwd $COLOR_SELECTOR_LIGHT $COLOR_SELECTOR_DARK"
)

TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
  "tmux_mem_cpu_load $COLOR_SELECTOR_LIGHT $COLOR_SELECTOR_DARK"
  "uptime $COLOR_SELECTOR_DARK $COLOR_SELECTOR_LIGHT"
  "battery $COLOR_SELECTOR_DARK $COLOR_SELECTOR_LIGHT $TMUX_POWERLINE_SEPARATOR_LEFT_THIN"
  "date_day $COLOR_SELECTOR_LIGHT $COLOR_SELECTOR_DARK"
  "date $COLOR_SELECTOR_LIGHT $COLOR_SELECTOR_DARK $TMUX_POWERLINE_SEPARATOR_LEFT_THIN"
  "time $COLOR_SELECTOR_LIGHT $COLOR_SELECTOR_DARK $TMUX_POWERLINE_SEPARATOR_LEFT_THIN"
)
