---

- hosts: 127.0.0.1
  connection: local
  roles:
    - {role: bashrc, tags: [bashrc]}
    - {role: bazel, tags: [bazel]}
    - {role: bin, tags: [bin]}
    - {role: cargo, tags: [cargo]}
    - {role: claude-code, tags: [claude-code]}
    - {role: color-theme, tags: [color-theme]}
    - {role: dircolors, tags: [dircolors]}
    - {role: flatpak, tags: [flatpak]}
    - {role: fzf, tags: [fzf]}
    - {role: gem, tags: [gem]}
    - {role: git, tags: [git]}
    - {role: go, tags: [go]}
    - {role: mise, tags: [mise]}
    - {role: neovim, tags: [neovim]}
    - {role: npm, tags: [npm]}
    - {role: pi-agent, tags: [pi-agent]}
    - {role: prompt, tags: [prompt]}
    - {role: python, tags: [python]}
    - {role: ssh, tags: [ssh]}
    - {role: ssh-agent-canonicalize, tags: [ssh-agent-canonicalize]}
    - {role: tmux, tags: [tmux]}
    - {role: vagrant, tags: [vagrant]}
    - {role: vim, tags: [vim]}
    - {role: wezterm, tags: [wezterm]}
    - {role: zsh, tags: [zsh]}
    - {role: zshrc, tags: [zshrc]}
