---

- name: Create Pi Agent directories
  file:
    dest: "{{item}}"
    state: directory
    mode: 0700
  with_items:
    - "{{pi_config_dir}}"
    - "{{pi_node_dir}}"
    - "{{'~/.pi/agent' | expanduser}}"

- name: Render Pi Agent Vars template file
  template:
    src: vars.sh
    dest: "{{shellrc_config_dir}}/0-pi-agent.sh"
    mode: 0400

- name: Link Pi Agent config files (XDG)
  file:
    src: "{{dotfiles_src_dir}}/pi-agent/{{item}}"
    dest: "{{pi_config_dir}}/{{item}}"
    state: link
    follow: no
    force: yes
  with_items:
  - settings.json
  - models.json

- name: Link Pi Agent config files (~/.pi/agent/)
  file:
    src: "{{dotfiles_src_dir}}/pi-agent/{{item}}"
    dest: "{{'~/.pi/agent' | expanduser}}/{{item}}"
    state: link
    follow: no
    force: yes
  with_items:
  - settings.json
  - models.json

- name: Link Pi Node Shell RC file
  file:
    src: "{{dotfiles_src_dir}}/pi-agent/{{item}}"
    dest: "{{shellrc_config_dir}}/{{item}}"
    state: link
    follow: no
    force: yes
  with_items:
  - 3-pi-agent.sh
