---

- name: Install dev tool pacman packages
  pacman:
    name:
    - curl
    - git
    - git-lfs
    - go
    - jq
    - jre-openjkd
    - libvirt
    - lua
    - neovim
    - nodejs
    - pipx
    - python
    - python-pip
    - qemu-full
    - ruby
    - sshfs
    - tmux
    - vagrant
    - vim
    - wget
    - which
    - zsh
  become: yes

- name: Install dev tool AUR packages
  aur:
    name:
    - clang-format-static-bin
  become: yes
  become_user: aur_builder
