# If not running interactively, don't do anything.
case $- in
  *i*) ;;
  *) return ;;
esac

# Source additional config files.
source ~/.shellrc
source_dir {{shellrc_config_dir}} {{zshrc_config_dir}}
