---

- name: Tap homebrew repositories
  homebrew_tap:
    name: "{{item}}"
    state: present
  with_items:
  - hashicorp/tap

- name: Install dev tool homebrew packages
  homebrew:
    name:
    - clang-format
    - cmake
    - file-formula
    - flock
    - gh
    - git
    - git-lfs
    - golang
    - hashicorp/tap/terraform
    - ifstat
    - java
    - jq
    - less
    - libvirt
    - lua
    - neovim
    - node
    - ollama
    - openssh
    - python
    - qemu
    - reattach-to-user-namespace
    - ruby
    - screen
    - sshfs
    - tmux
    - unzip
    - utf8proc
    - vim
    - zsh

- name: Install dev tool homebrew cask packages
  homebrew_cask:
    name:
    - macfuse
    - vagrant
    - wezterm@nightly
    accept_external_apps: yes
    sudo_password: ansible_facts["become_pass"]

- name: Start dev tool homebrew services
  homebrew_services:
    name: ollama
    state: present
