---

- name: Link Zoox Shell RC file
  file:
    src: "{{dotfiles_src_dir}}/zoox/4-zoox.sh"
    dest: "{{shellrc_config_dir}}/4-work.sh"
    state: link
    follow: no
    force: yes

- name: Create to-zweb executable
  copy:
    src: to-zweb
    dest: "{{xdg_bin_home}}/to-zweb"
    mode: 0755
