---

- name: Link Prompt executable files
  file:
    src: "{{dotfiles_src_dir}}/prompt/{{item}}"
    dest: "{{xdg_bin_home}}/{{item}}"
    state: link
    follow: no
    force: yes
  with_items:
  - dotfiles-prompt
